version: '2'
services:
  postgres:
    image: "postgres"
    container_name: "doc_postgres"
    ports:
      - "5432:5432"
    volumes:
      - doc_postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
volumes:
  doc_postgres_data:
